version: "3.8"

services:
  app:
    image: maven:3.8.4-jdk-17 # o tu propia imagen de la app healthtrack
    working_dir: /usr/src/app
    volumes:
      - ../src:/usr/src/app/src
      - ../pom.xml:/usr/src/app/pom.xml
    command: mvn spring-boot:run # o como arranques tu servidor en 8080
    networks:
      - healthtrack-network

  jmeter:
    image: justb4/jmeter:5.5
    depends_on:
      - app
    volumes:
      - ./jmeter:/jmeter
    command: >
      -n -t /jmeter/performance_test.jmx
      -l /jmeter/resultados.jtl
      -e -o /jmeter/report
    networks:
      - healthtrack-network

networks:
  healthtrack-network:
    driver: bridge
